import {EMPTY_STRING} from "../constants/api/common";
import { GET_USER_FULL_INFO, SET_NEED_USER_ID} from "../constants/actions/actions_const";

const initialState = {
    id: EMPTY_STRING,                //string(autogenerated)
    title: EMPTY_STRING,             //string("mr", "ms", "mrs", "miss", "dr", "")
    firstName: EMPTY_STRING,         //string(length: 2-50)
    lastName: EMPTY_STRING,          //string(length: 2-50)
    gender: EMPTY_STRING,             //string("male", "female", "other", "")
    email: EMPTY_STRING,             //string(email)
    dateOfBirth: EMPTY_STRING,        //string(ISO Date - value: 1/1/1900 - now)
    registerDate: EMPTY_STRING,       // string(autogenerated)
    phone: EMPTY_STRING,              //string(phone number - any format)
    picture: EMPTY_STRING,            //(url)
    location: EMPTY_STRING,           //object(Location)
    needUserId: EMPTY_STRING,         //пользователь, инфо по которому нужно получить

};

const personalAreaReducer=(state=initialState, action)=>{
    switch (action.type){
        case GET_USER_FULL_INFO:return{
            id: action.payload.id,
            title: action.payload.title,
            firstName: action.payload.firstName,
            lastName: action.payload.lastName,
            gender: action.payload.gender,
            email: action.payload.email,
            dateOfBirth: action.payload.dateOfBirth,
            registerDate: action.payload.registerDate,
            phone: action.payload.phone,
            picture: action.payload.picture,
            location: action.payload.location,
        }
        case SET_NEED_USER_ID:return {
            needUserId: action.payload,
        }

        default:
            return state;
    }
}

export default personalAreaReducer;